import { Rubik } from "next/font/google";
import "./globals.css";
import Banner from "@/components/banner";
import Footer from "@/components/layouts/Footer";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "sonner";

export const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-rubik",
  display: "swap",
});

export const metadata = {
  title: "Roots Landscape Company",
  description: "Generated by create Roots Landscape Company",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body className={rubik.className}>
        <QueryProvider>{children}</QueryProvider>
        <Toaster position="top-center" richColors closeButton />
      </body>
    </html>
  );
}
